
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./docker/app.env
    depends_on:
      - db
      - cache

  db:
    container_name: postgre
    image: postgres:16.3
    environment:
      POSTGRES_DB: worklinker
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  cache:
    image: redis:8.0.1
    ports:
      - "6379:6379"