name: Deploy Backend to GCP

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Make gradlew executable
        working-directory: ./backend
        run: chmod +x gradlew

      - name: Run tests
        working-directory: ./backend
        run: ./gradlew test

      - name: Copy to VM 1
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.GCP_VM_IP_1 }}
          username: ${{ secrets.GCP_SSH_USER }}
          key: ${{ secrets.GCP_SSH_PASSWORD }}
          source: "./backend*"
          target: "/tmp/backend"

      - name: Copy to VM 2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.GCP_VM_IP_2 }}
          username: ${{ secrets.GCP_SSH_USER }}
          key: ${{ secrets.GCP_SSH_PASSWORD }}
          source: "./backend*"
          target: "/tmp/backend"

      - name: Deploy Docker Compose on VM1
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_VM_IP_1 }}
          username: ${{ secrets.GCP_SSH_USER }}
          key: ${{ secrets.GCP_SSH_PASSWORD }}
          script: |
            cd /tmp/backend
            sudo docker compose up -d --build backend

      - name: Deploy Docker Compose on VM2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_VM_IP_2 }}
          username: ${{ secrets.GCP_SSH_USER }}
          key: ${{ secrets.GCP_SSH_PASSWORD }}
          script: |
            cd /tmp/backend
            sudo docker compose up -d --build backend
