name: Deploy static site to Google Cloud VM

on:
  push:
    branches: [ main ]  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Copy files to GCP VM via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_SSH_USER }}
          key: ${{ secrets.GCP_SSH_PASSWORD }}
          source: "./front*"       
          target: "/tmp/site"  

      - name: Deploy to nginx web root
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_SSH_USER }}
          key: ${{ secrets.GCP_SSH_PASSWORD }}
          script: |
            sudo rm -rf /var/www/html/*
            sudo cp -r /tmp/site/* /var/www/html/
            sudo rm -rf /tmp/site
